translate_task:
  description: >
    Translate {sentence} from English to Korean without any mistakes or misunderstandings
  expected_output: >
    A well formatted and grammatically correct translation from English to Korean using proper capitalization of names and places.
  agent: translator_agent

count_task:
  description: >
    Count the amount of letters a sentence.
  expected_output: >
    The number of letters in a sentence.
  agent: counter_agent